namespace: capg-system

namePrefix: capg-

# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-gcp"

resources:
  - ../../config/default/credentials.yaml

bases:
  - ../../config/manager

patchesStrategicMerge:
  # Provide customizable hook for make targets.
  - ../../config/default/manager_image_patch.yaml
  - ../../config/default/manager_pull_policy.yaml
  - ../../config/default/manager_credentials_patch.yaml

patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_healthcheck.yaml