apiVersion: v1
data:
  credentials.json: ${GCP_B64ENCODED_CREDENTIALS}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  name: capg-manager-bootstrap-credentials
  namespace: capg-system
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
    control-plane: capg-controller-manager
  name: capg-controller-manager
  namespace: capg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-gcp
      control-plane: capg-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-logs-container: manager
      labels:
        cluster.x-k8s.io/provider: infrastructure-gcp
        control-plane: capg-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --leader-elect
        - --metrics-bind-addr=127.0.0.1:8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /home/.gcp/credentials.json
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/spectro-images-public/cluster-api-gcp/test/cluster-api-gcp-controller:v1alpha4
        imagePullPolicy: Always
        name: manager
        volumeMounts:
        - mountPath: /home/.gcp
          name: credentials
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: credentials
        secret:
          secretName: capg-manager-bootstrap-credentials
