namespace: capi-webhook-system

namePrefix: capg-

# Labels to add to all resources and selectors.

#resources:
#  - ../../config/default/namespace.yaml
#  - ../../config/default/credentials.yaml



vars:
- fieldref:
    fieldPath: metadata.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref: {}
  name: CERTIFICATE_NAME
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref:
    fieldPath: metadata.namespace
  name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: webhook-service
    version: v1
- fieldref: {}
  name: SERVICE_NAME
  objref:
    kind: Service
    name: webhook-service
    version: v1

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../config/crd
- ../../config/manager
- ../../config/webhook
- ../../config/certmanager
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-gcp
patches:
- path: patch_service_account.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
- path: ../../config/default/manager_image_patch.yaml
- path: ../../config/default/manager_pull_policy.yaml
- path: ../../config/default/manager_webhook_patch.yaml
- path: ../../config/default/webhookcainjection_patch.yaml
