# add public code coverage reports
name: coverage

on:
  push:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - run: "make test-cover"

    - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
      with:
        file: ./coverage.out
        fail_ci_if_error: true
